### ISSUE TITLE
Search results sortable by rating count

### ISSUE THREAD

**Issue by beefsack** [Mitcheljager/workshop.codes#12]
Hello, wonderful project!

I've really been wanting search results to be sortable somehow based on popularity or ratings. Did you already have plans for this? Or perhaps some suggestion on how you'd like someone to go about it?

Personal opinion, but I think being able to sort based on recent ratings is a great way to filter to what is currently the most popular mode, such as filtering to ratings in the past month.

**Comment by Mitcheljager** [comment]
Hi! Sorry for the late reply, turns out I didn't have notifications enabled.

I do believe what you are asking is already there. When clicking the "+ More filters" buttons under the searchbar, you can sort your search query by a number of things. "On fire" more than likely does what you want. "On fire" is a combination of views, clicks on the "copy code" button, and favorites in the last 7 days.

![image](https://user-images.githubusercontent.com/12848235/79126796-eba63880-7da0-11ea-9b90-f2d7c2c9beab.png)
